baseURL = 'https://www.samueljhuff.com'
languageCode = 'en-us'
title = 'UPnP Explorer'

[[menus.main]]
name = 'home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'about'
pageRef = '/about'
weight = 20

[[menus.main]]
name = 'projects'
pageRef = '/projects'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
